AndyFranklin\FaqBundle\Entity\Answer:
  type: entity
  table: answer
  id:
    id:
      id: true
      type: integer
      generator:
        strategy: IDENTITY
  fields:
    body:
      type: string
    createdAt:
      type: datetime
    updatedAt:
      type: datetime
    rating:
      type: integer
    published:
      type: boolean
