AndyFranklin\FaqBundle\Entity\Answer:
  repositoryClass: AndyFranklin\FaqBundle\Repository\AnswerRepository
  type: entity
  table: answer
  gedmo:
    soft_deleteable:
      field_name: deletedAt
      time_aware: false
      hard_delete: true
  id:
    id:
      id: true
      type: integer
      generator:
        strategy: IDENTITY
  fields:
    body:
      type: string
    createdAt:
      type: datetime
      gedmo:
        timestampable:
          on: create
    updatedAt:
      type: datetime
      gedmo:
        timestampable:
          on: update
    rating:
      type: integer
    published:
      type: boolean
    deletedAt:
      type: datetime
      nullable: true
  manyToOne:
    question:
      targetEntity: AndyFranklin\FaqBundle\Entity\Question
      inversedBy: answers