AndyFranklin\FaqBundle\Entity\Category:
  type: entity
  table: category
  gedmo:
    soft_deleteable:
      field_name: deletedAt
      time_aware: false
      hard_delete: true
  id:
    id:
      id: true
      type: integer
      generator:
        strategy: IDENTITY
  fields:
    title:
      type: string
    createdAt:
      type: datetime
      gedmo:
        timestampable:
          on: create
    updatedAt:
      type: datetime
      gedmo:
        timestampable:
          on: update
    published:
      type: boolean
    slug:
      type: string
      gedmo:
        slug:
          separator: _
          style: camel
          fields:
            - title
    deletedAt:
      type: datetime
      nullable: true
  manyToOne:
    question:
      targetEntity: AndyFranklin\FaqBundle\Entity\Question
      inversedBy: categories