AndyFranklin\FaqBundle\Entity\Question:
  type: entity
  table: question
  gedmo:
    soft_deleteable:
      field_name: deletedAt
      time_aware: false
      hard_delete: true
  id:
    id:
      id: true
      type: integer
      generator:
        strategy: IDENTITY
  fields:
    title:
      type: string
    createdAt:
      type: datetime
      gedmo:
        timestampable:
          on: create
    updatedAt:
      type: datetime
      gedmo:
        timestampable:
          on: update
    ranking:
      type: integer
    rating:
      type: integer
    published:
      type: boolean
    slug:
      type: string
      length: 50
      gedmo:
        slug:
          separator: _
          style: lower
          fields:
            - title
    deletedAt:
      type: datetime
      nullable: true
  oneToMany:
    answers:
      targetEntity: AndyFranklin\FaqBundle\Entity\Answer
      mappedBy: question
    categories:
      targetEntity: AndyFranklin\FaqBundle\Entity\Category
      mappedBy: question
