AndyFranklin\FaqBundle\Entity\Search:
  type: entity
  table: search
  gedmo:
    soft_deleteable:
      field_name: deletedAt
      time_aware: false
      hard_delete: true
  id:
    id:
      id: true
      type: integer
      generator:
        strategy: IDENTITY
  fields:
    query:
      type: string
    count:
      type: integer
    createdAt:
      type: datetime
      gedmo:
        timestampable:
          on: create
    updatedAt:
      type: datetime
      gedmo:
        timestampable:
          on: update
    published:
      type: boolean
    deletedAt:
      type: datetime
      nullable: true