AndyFranklin\FaqBundle\Entity\Answer:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: body
    properties:
        body:
            - NotNull: ~
            - Length:
                min: 15
                max: 1000
        question:
            - NotNull: ~
