AndyFranklin\FaqBundle\Entity\Category:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: title
    properties:
        title:
            - NotNull: ~
            - Length:
                min: 3
                max: 20
