AndyFranklin\FaqBundle\Entity\Question:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: [title, category]
    properties:
        title:
            - NotNull: ~
            - Length:
                min: 30
                max: 250
