question_create:
    path: /question
    defaults: { _controller: AndyFranklinFaqBundle:Question:create }
    methods: [POST]

question_get_by_slug:
    path: /question/slug/{slug}
    defaults: { _controller: AndyFranklinFaqBundle:Question:singleSlug }

question_get:
    path: /question/{id}
    defaults: { _controller: AndyFranklinFaqBundle:Question:singleId }
    methods: [GET]
    requirements:
        id: '\d+'

question_add_category:
    path: /question/{id}/category
    defaults: { _controller: AndyFranklinFaqBundle:Question:addCategory }
    methods: [POST]
    requirements:
        id: '\d+'

question_up_rating:
    path: /question/{id}/rating/up
    defaults: { _controller: AndyFranklinFaqBundle:Question:upRate }
    methods: [GET]

question_down_rating:
    path: /question/{id}/rating/down
    defaults: { _controller: AndyFranklinFaqBundle:Question:downRate }
    methods: [GET]

answer_create:
    path: /answer
    defaults: { _controller: AndyFranklinFaqBundle:Answer:create }
    methods: [POST]

answer_up_rating:
    path: /answer/{id}/rating/up
    defaults: { _controller: AndyFranklinFaqBundle:Answer:upRate }
    methods: [GET]

answer_down_rating:
    path: /answer/{id}/rating/down
    defaults: { _controller: AndyFranklinFaqBundle:Answer:downRate }
    methods: [GET]



category_create:
    path: /category
    defaults: { _controller: AndyFranklinFaqBundle:Category:create }
    methods: [POST]