question_create:
    path: /question/create
    defaults: { _controller: AndyFranklinFaqBundle:Question:create }

question_get:
    path: /question/slug/{slug}
    defaults: { _controller: AndyFranklinFaqBundle:Question:singleSlug }
