services:
    AndyFranklin\FaqBundle\Controller\QuestionController:
        class: AndyFranklin\FaqBundle\Controller\QuestionController
        public: true
        arguments: ['@fos_rest.view_handler', '@Doctrine\ORM\EntityManagerInterface']
