services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    AndyFranklin\FaqBundle\:
        resource: '../../*'
        exclude: '../../{Entity,Tests,Repository,Exception}'

    AndyFranklin\FaqBundle\Controller\:
        resource: '../../Controller'
        public: true
        tags: ['controller.service_arguments']

    AndyFranklin\FaqBundle\Form\Extension\HttpFoundation\HttpFoundationRequestHandler:
        decorates: form.type_extension.form.request_handler
        decoration_priority: 256
        public: false

    AndyFranklin\FaqBundle\Repository\QuestionRepository:
        factory: 'doctrine.orm.entity_manager:getRepository'
        arguments: ['AndyFranklin\FaqBundle\Entity\Question']

    AndyFranklin\FaqBundle\Repository\AnswerRepository:
        factory: 'doctrine.orm.entity_manager:getRepository'
        arguments: ['AndyFranklin\FaqBundle\Entity\Answer']